# Tasks to check if db has been initialized already
#

- name: Check if init lock file exists
  stat:
    path: '{{postgres_init_lock_file}}'
  register: out

- set_fact:
    db_initialized: false # default

- set_fact:
    db_initialized: true
  when: out.stat.exists  
 
