# This sequence of tasks runs the required sqls and loads DB with test data
- debug:
    msg: 'DML init for {{pg_db_name}} db'

- name: '{{pg_db_name}}: Update ip address in postgres dml init files'
  lineinfile:
    path: '{{pg_sql_path}}/{{pg_db_name}}/{{pg_db_name}}_deploy.properties'
    regexp: '^DB_SERVERIP='
    line: DB_SERVERIP={{postgres.host}}
   
- name: '{{pg_db_name}}: Update port in postgres dml init files'
  lineinfile:
    path: '{{pg_sql_path}}/{{pg_db_name}}/{{pg_db_name}}_deploy.properties'
    regexp: '^DB_PORT='
    line: DB_PORT={{postgres.port}}  # Defined in all.yml

- name: '{{pg_db_name}}: Update basepath in postgres dml init files' 
  lineinfile:
    path: '{{pg_sql_path}}/{{pg_db_name}}/{{pg_db_name}}_deploy.properties'
    regexp: '^BASEPATH='
    line: BASEPATH={{pg_sql_path}}

- name: '{{pg_db_name}}: Update log path in postgres init dml files' 
  lineinfile:
    path: '{{pg_sql_path}}/{{pg_db_name}}/{{pg_db_name}}_deploy.properties'
    regexp: '^LOG_PATH='
    line: LOG_PATH={{logs_dir}}/

# Pass all passwords via env variables.
- name: 'Run {{pg_db_name}} shell script'
  shell: 'bash {{pg_db_name}}_dml_deploy.sh {{pg_db_name}}_deploy.properties'
  environment:
    SU_USER_PWD: '{{secrets.postgres.su}}'
    SYSADMIN_PWD: '{{secrets.postgres.sysadmin}}'
    DBADMIN_PWD: '{{secrets.postgres.dbadmin}}'
    APPADMIN_PWD: '{{secrets.postgres.appadmin}}'
    DBUSER_PWD: '{{secrets.postgres.dbuser}}'
  args:
    chdir: '{{pg_sql_path}}/{{pg_db_name}}'
