---
# This script runs all the init SQL queries and populates all tables with
# test data 
# IMPORTANT: Init only run once.  To run again, delete the init.lock file in 
# postgres folder

# Copy dml files - typically needed to replace default master data with 
# country's data
#

- name: Chekc if postgres has already been initialized
  block:  # This block only applies to internal postgres which is part of cluster
  - name: Check if init lock file exists (ie. init has already been done once)
    stat:
      path: '{{postgres_init_lock_file}}'
    become: yes
    register: out
  
  - debug:
      msg: Init has already been done once. Skipping init.
    when: out.stat.exists
    
  - meta: end_play  # Exit
    when: out.stat.exists
  when: postgres.external == false 

- include: init_ddl.yml
  vars:
    pg_db_name: '{{item.key}}'
    pg_sql_path: '{{item.value.sql_path}}'
  with_items: '{{databases | dict2items}}'

- include: init_dml.yml
  vars:
    pg_db_name: '{{item.key}}'
    pg_sql_path: '{{item.value.dml_path}}'
  when: item.value.dml_path is defined
  loop: '{{databases | dict2items}}'
        
# After successful init, create a lockfile to not init again. Applicable only for internal DB.
- name: Create init lock file to not re-init again
  file:
    path: '{{postgres_init_lock_file}}'
    state: touch
  become: yes
  when: postgres.external == false 
