---

- name: Check if kubeadm has already run
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Init cluster if needed
  include_tasks: init.yml
  when: not kubeadm_ca.stat.exists
  run_once: yes

- name: Enable and check kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
  register: started_kubelet

- name: Make sure .kube file is present on console
  file:
    name: "{{ansible_env.HOME}}/.kube"
    state: directory

- name: Copy config file to console machine for kubectl
  fetch:
    src: '{{kubeadmin_config}}'
    dest: '{{console_kubeadmin_config_path}}'
    flat: yes
  run_once: yes
  ignore_errors: yes

