---
{{ if eq .Values.localRepo.enabled true }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.localRepo.pvc.name }} 
spec:
  storageClassName: {{ .Values.localRepo.sc.name }} 
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.localRepo.pvc.size }} 
  selector:
    matchLabels:
      name: {{ .Values.localRepo.pv.name }} 
{{ end }}
