apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }} 
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - port: {{ .Values.docker.servicePort }} 
      targetPort: {{ .Values.docker.containerPort }}
