{{ if eq .Values.localRepo.enabled true }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.localRepo.pv.name }} 
  labels:
    name: {{ .Values.localRepo.pv.name }} 
spec:
  storageClassName: {{ .Values.localRepo.sc.name }} 
  capacity:
    storage: {{ .Values.localRepo.pv.size }}
  accessModes:
    - ReadOnlyMany
  nfs:
    server:  {{ .Values.localRepo.nfs.server }}
    path: {{ .Values.localRepo.nfs.path }} 
{{ end }}
