
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kibana
  namespace: {{ .Release.Namespace }} 
  annotations:
    ingress.kubernetes.io/class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /kibana(/|$)(.*)
        backend:
          serviceName: {{ template "kibana.fullname" . }}
          servicePort: {{ .Values.service.port }} 
