
- name: First remove pip installation (otherwise certbot gives issues)
  pip:
    name: requests
    state: absent
  become: yes

- name: Uninstall yum installation
  yum:
    name: python-requests
    state: absent 
  become: yes

- name: Re-install with yum
  yum:
    name: python-requests
    state: present
  become: yes

