---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}

spec:
  selector:
    app: {{ .Values.name }}
  type: NodePort
  ports:
    - name: api-port
      port: {{ .Values.docker.servicePort }}
      targetPort: {{ .Values.docker.containerPort }}
      nodePort: {{ .Values.docker.nodeport}}	

    - name: web-console-port
      port: {{ .Values.docker.webPort }}
      targetPort: {{ .Values.docker.webport }}
