# Main role to checkout git repo - private or public
#   Inputs:
#     repo_path: Full path e.g https://github.com/username/reponame
#     repo_dest: Destination folder
#     version: branch or tag to checkout
#     githubuser
#     githubpassword

- name: git checkout 
  expect: 
    command: 'git clone -b {{version}} -q {{repo_path}} {{repo_dest}}'
    responses:
      Username: '{{githubuser}}'
      Password: '{{githubpassword}}'
    timeout: 600
  ignore_errors: yes
  no_log: true

