# Activemq installation
#

- hosts: console
  vars:
    kube_config: '{{clusters.mz.kube_config}}' 
    install_name: 'activemq' 
    helm_chart: '{{charts_root}}/activemq'
    is_template: true  
    helm_namespace: default
    helm_values: '{{charts_root}}/activemq/values.template.j2'
    helm_strings: ''
  roles:
    - {role:  helm}

