- hosts: '{{cluster}}'
  become: yes
  gather_facts: yes
  vars_files: '{{install_root}}/group_vars/k8s.yml'
  roles:
    - { role: k8scluster/docker, tags: docker }
    - { role: packages/git, tags: git }

- hosts: '{{master}}'  # Master 
  gather_facts: yes
  vars_files: '{{install_root}}/group_vars/k8s.yml'
  become: yes
  roles:
    - { role: k8scluster/kubernetes/master, tags: master }
    - { role: k8scluster/cni, tags: cni }

- hosts: '{{workers}}' # Workers
  gather_facts: yes
  vars_files: '{{install_root}}/group_vars/k8s.yml'
  become: yes
  roles:
    - { role: k8scluster/kubernetes/node, tags: node }

- hosts: '{{master}}'  # Master 
  gather_facts: yes
  vars_files: '{{install_root}}/group_vars/k8s.yml'
  become: yes
  tasks:
    - name: "MetalLB role"
      include_role:
        name: k8scluster/metallb
      when: "additional_features.metallb"
      run_once: yes
      tags: metallb

    - name: "Healthcheck role"
      include_role:
        name: k8scluster/healthcheck
      when: "additional_features.healthcheck"
      run_once: yes
      tags: healthcheck

