# Antivirus running on MZ. 
#

- hosts: console
  vars:
    kube_config: '{{clusters.dmz.kube_config}}' 
    install_name: 'clamav' 
    helm_chart: '{{charts_root}}/clamav'
    is_template: true  
    helm_namespace: default
    helm_values: '{{charts_root}}/clamav/values.template.j2'
    helm_strings: ''
  roles:
    - {role:  helm}

