# Metrics-server
- import_playbook: metrics.yml
  vars:
    kube_config: '{{clusters.dmz.kube_config}}'

# Prometheus
- import_playbook: prometheus.yml
  vars:
    kube_config: '{{clusters.dmz.kube_config}}'
    mon_prop: '{{clusters.dmz.monitoring}}' 

# Grafana
- import_playbook: grafana.yml
  vars:
    kube_config: '{{clusters.dmz.kube_config}}'
    mon_prop: '{{clusters.dmz.monitoring}}' 

# ELK - Filebeat
# Only Filebeat component installed on DMZ. It pushes logs to 
# Elasticsearch on MZ.
- import_playbook: filebeat.yml
  vars:
    mon_prop: '{{clusters.dmz.monitoring}}' 
    kube_config: '{{clusters.dmz.kube_config}}'
