# Playbook to install ELK component Elasticsearch
# input: kube_config
#

# Install Elasticsearch
- hosts: console
  vars:
    kube_config: '{{kube_config}}'
    install_name: elasticsearch 
    helm_chart: '{{charts_root}}/elasticsearch'
    is_template: true
    helm_namespace: monitoring
    helm_values: '{{charts_root}}/elasticsearch/values.template.j2'
    helm_strings: ''
  roles:
    - {role:  helm}

