# Metrics-server
- import_playbook: metrics.yml
  vars:
    kube_config: '{{clusters.mz.kube_config}}'

# Prometheus
- import_playbook: prometheus.yml
  vars:
    kube_config: '{{clusters.mz.kube_config}}'
    mon_prop: '{{clusters.mz.monitoring}}' 

# Grafana
- import_playbook: grafana.yml
  vars:
    kube_config: '{{clusters.mz.kube_config}}'
    mon_prop: '{{clusters.mz.monitoring}}' 

# ELK - Elasticsearch
- import_playbook: elasticsearch.yml
  vars:
    kube_config: '{{clusters.mz.kube_config}}'

# ELK - Kibana
- import_playbook: kibana.yml
  vars:
    kube_config: '{{clusters.mz.kube_config}}'

# ELK - Filebeat
# Filebeat must be installed after Kibana so that readymade available
# dashboards may be loaded to Kibana
- import_playbook: filebeat.yml
  vars:
    mon_prop: '{{clusters.mz.monitoring}}' 
    kube_config: '{{clusters.mz.kube_config}}'
