# Playbook to install NFS Server and prepare all machines
# for nfs client
- hosts: all  # nfs-utils needed on all machines
  roles:
    - {role: packages/nfs-utils}

- hosts: console
  roles:
    - {role: nfs-server}


