# Playbook to install reg-client downloader
# Inputs:
#   kube_config  



# Prepare folders on nfs
- hosts: console
  gather_facts: true
  vars:
    reg_prop: '{{reg_client}}'
  roles:
    - {role: reg-client-prep}

# Convert helm template to helm values 
- hosts: console
  vars:
    kube_config: '{{clusters.dmz.kube_config}}'
    install_name: 'reg-client-downloader' 
    helm_chart: '{{charts_root}}/reg-client-downloader'
    is_template: true  
    helm_namespace: 'default'
    helm_values: '{{charts_root}}/reg-client-downloader/values.template.j2'
    helm_strings: ''
  roles:
    - {role:  helm}

