# This playbook apply any taints to nodes.  Taints are needed to 
# make some pods run exclusively on a node. This playbook must be 
# called immediately after a cluster is setup.  taints are applied only if they 
# are enabled. Know what you are doing!  Taints will not let any other pods
# schedule on the nodes.
#
# Apply any taints
- hosts: console
  vars:
    kube_config: '{{clusters.mz.kube_config}}' 
  tasks:
    # Enable postgres taint 
    - name: Enable postgres taint    
      shell: 'kubectl --kubeconfig {{kube_config}} taint nodes {{postgres.node_affinity.node}} {{ postgres.node_affinity.taint.key}}={{postgres.node_affinity.taint.value}}:NoSchedule  --overwrite=true'         
      when: postgres.node_affinity.enabled == true
    
    # Or disable taint
    - name: Disable postgres taint 
      shell: 'kubectl --kubeconfig {{kube_config}} taint nodes {{postgres.node_affinity.node}} {{ postgres.node_affinity.taint.key}}:NoSchedule-'         
      when: postgres.node_affinity.enabled != true
      ignore_errors: yes

    # Enable hdfs  taint 
    - name: Enable hdfs taint    
      shell: 'kubectl --kubeconfig {{kube_config}} taint nodes {{hdfs.node_affinity.node}} {{ hdfs.node_affinity.taint.key}}={{hdfs.node_affinity.taint.value}}:NoSchedule --overwrite=true'         
      when: hdfs.node_affinity.enabled == true
    
    # Or disable taint
    - name: Disable hdfs taint    
      shell: 'kubectl --kubeconfig {{kube_config}} taint nodes {{hdfs.node_affinity.node}} {{ hdfs.node_affinity.taint.key}}:NoSchedule-'         
      when: hdfs.node_affinity.enabled != true
      ignore_errors: yes

    # Enable minio  taint 
    - name: Enable minio taint    
      shell: 'kubectl --kubeconfig {{kube_config}} taint nodes {{minio.node_affinity.node}} {{ minio.node_affinity.taint.key}}={{minio.node_affinity.taint.value}}:NoSchedule --overwrite=true'         
      when: minio.node_affinity.enabled == true
    
    # Or disable taint
    - name: Disable minio taint    
      shell: 'kubectl --kubeconfig {{kube_config}} taint nodes {{minio.node_affinity.node}} {{ minio.node_affinity.taint.key}}:NoSchedule-'         
      when: minio.node_affinity.enabled != true
      ignore_errors: yes
