
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: elasticsearch
  namespace: {{ .Release.Namespace }} 
  annotations:
    ingress.kubernetes.io/class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /elasticsearch(/|$)(.*)
        backend:
          serviceName: {{ template "elasticsearch.masterService" . }}
          servicePort: {{ .Values.httpPort }} 
