---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.docker.service }}
  namespace: {{ .Release.Namespace }} 

spec:
  selector:
    app: {{ .Values.docker.service }}
  ports:
    - port: 80 
      targetPort: {{ .Values.docker.containerPort }}
