apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }} 
  namespace: {{ .Release.Namespace }} 
spec:
  selector:
    app: {{ .Values.name }} 
  ports:
    - port: {{ .Values.servicePort }} 
      targetPort: {{ .Values.containerPort }}
