
- name: Uninstall pip urllib3 (otherwise certbot gives issues)
  pip:
    name: urllib3
    state: absent
  become: yes

- name: Uninstall urllib3 with yum
  yum:
    name: python-urllib3
    state: absent
  become: yes

- name: Re-install urllib3 with yum
  yum:
    name: python-urllib3
    state: present
  become: yes


