apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.print.serviceName }} 
  namespace: {{ .Release.Namespace }} 
spec:
  ports:
  - port: {{ .Values.services.print.servicePort }}
    targetPort: {{ .Values.services.print.containerPort }}
  selector:
    app: {{ .Values.services.print.serviceName }} 

