apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.notifier.serviceName }} 
  namespace: {{ .Release.Namespace }} 
  labels:
    app: {{ .Values.services.notifier.serviceName }}
    component: {{ .Values.component }} 
    
spec:
  replicas: {{ .Values.services.notifier.podconfig.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.services.notifier.serviceName }} 
  minReadySeconds: {{ .Values.services.notifier.podconfig.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.services.notifier.podconfig.maxUnavailable }}
      maxSurge: {{ .Values.services.notifier.podconfig.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.notifier.serviceName }} 
        component: {{ .Values.component }} 
        exportLogs: {{ .Values.exportLogs }}
    spec:
      {{- include "dockerHubSecret" .  | indent 6}}
      containers:
      - name: {{ .Values.services.notifier.serviceName }} 
        image: {{ .Values.services.notifier.dockerImage }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        - name: active_profile_env
          value: {{ .Values.activeProfileEnv }} 
        - name: spring_config_label_env
          value: {{ .Values.springConfigLabel }} 
        - name: spring_config_url_env
          value: {{ .Values.configServerUrl }} 
        - name: artifactory_url_env
          value: {{ .Values.artifactoryUrl }} 
        - name: is_glowroot_env
          value: {{ .Values.isGlowroot }} 
        - name: runtime_dep_url_env
          value: {{ .Values.runtimeDepUrl }}
        ports:
        - containerPort: {{ .Values.services.notifier.containerPort }}
#        readinessProbe:  # TODO: Disabled. for some reason not working.
#          httpGet:
#            path: {{ .Values.services.notifier.healthUrl }} 
#            port: {{ .Values.services.notifier.containerPort }} 
#          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
#          periodSeconds: {{ .Values.probe.period }} 
#        livenessProbe:
#          httpGet:
#            path: {{ .Values.services.notifier.healthUrl }} 
#            port: {{ .Values.services.notifier.containerPort }} 
#          initialDelaySeconds: {{ .Values.probe.initialDelay }} 
#          periodSeconds: {{ .Values.probe.period }}
