# We have written a separate ingress for keycloak 'cause it requires
# a different rewrite rule.  We want keycloak url to be 
# https://public_server/keycloak/auth/, rather than
# https://public_server/auth/.  Not that last slash is important!

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: minio
  namespace: {{ .Release.Namespace }}
  annotations:
    ingress.kubernetes.io/class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /minio  # To browser
        backend:
          serviceName: {{ template "minio.fullname" . }}
          servicePort: {{ .Values.service.port }} 
