# Delete monitoring  persistence
- hosts: console
  gather_facts: no
  become: yes
  vars_prompt:
    - name: sure 
      prompt: 'Do you want to ERASE all Prometheus and Grafana data? Are you sure? (yes/no)'
      private: no
  tasks:
  - name: Delete moniotoring folders
    block:
      - name: Find all monitoring folders 
        find:
          paths: '{{nfs.folder}}' 
          patterns: 'monitoring*'
          file_type: directory
        register: dirs_to_be_deleted

#      - debug:
#          msg: '{{dirs_to_be_deleted.files}}'
    
      - name: Delete all monitoring related folders
        file:
          path: "{{ item.path }}"
          state: absent
        with_items: "{{ dirs_to_be_deleted.files }}"
    when: sure.lower().strip() == 'yes'

