# Reset config repo
- hosts: console
  gather_facts: no
  become: yes
  vars_prompt:
    - name: sure 
      prompt: 'Do you want to ERASE CONFIG REPO? Are you sure? (yes/no)' 
      private: no
  tasks:
    - name: Delete config repo
      file: 
        path: '{{config_repo.local_git_repo.path}}'
        state: absent     
      when: sure.lower().strip() == 'yes' 
