---
- hosts: '{{cluster}}'
  gather_facts: no
  vars_files: '{{install_root}}/group_vars/k8s.yml'
  become: yes
  vars_prompt:
    - name: sure 
      prompt: 'Are you sure want to delete cluster {{cluster}}? This will ERASE EVERYTHING! (yes/no) '
      private: no
  tasks:
    - name: Reset
      block: 
        - name: Reset Kubernetes component
          shell: "kubeadm reset --force"
          ignore_errors: True
        
        - name: Stop kubelet 
          systemd:
            name: kubelet
            state: stopped

        - name: Stop docker
          systemd:
            name: docker
            state: stopped

        - name: Remove various links 
          file:
            path: /var/lib/cni 
            state: absent
          ignore_errors: True

        - name: Remove various links 
          file:
            path: /var/lib/kubelet/*
            state: absent
          ignore_errors: True

        - name: Remove various links 
          file:
            path: /etc/cni/
            state: absent
          ignore_errors: True

        - name: Remove interfaces
          command: 'ifconfig cni0 down' 
          ignore_errors: True

        - name: Remove interfaces
          command: 'ifconfig flannel.1 down' 
          ignore_errors: True

        - name: Remove interfaces
          command: 'ifconfig docker0 down' 
          ignore_errors: True

        - name: Delete flannel.1 interface
          command: ip link delete flannel.1
          when: network == "flannel" or network == "canal"
          ignore_errors: True
    
        - name: Delete cni0 interface
          command: ip link delete cni0
          when: network == "flannel"
          ignore_errors: True

      when: sure.lower().strip() == 'yes'
