# https://medium.com/@getpagespeed/fix-importerror-pyopenssl-module-missing-required-functionality-e1c514797204
- name: Un-install pip installation (otherwise certbot gives issues)
  pip:
    name: six
    state: absent
  become: yes

- name: Uninstall six with yum
  yum:
    name: python-six
    state: absent 
  become: yes

- name: Re-install six with yum
  yum:
    name: python-six
    state: present 
  become: yes

