---
- name: Recreate kube-dns
  command: kubectl --kubeconfig={{ kubeadmin_config }} -n kube-system delete pods -l k8s-app=kube-dns
  delegate_to: "{{ cluster_master }}"
  run_once: true
  ignore_errors: true
